In [1]:
import pandas as pd

In [2]:
alien_data = pd.read_csv("data/sightings_count.csv")

In [3]:
alien_data

,state_long,state_short,sightings_total,Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec
0,Alabama,AL,34,3,2,4,5,4,2,3,3,3,1,2,2
1,Arizona,AZ,155,12,20,20,13,15,10,6,8,11,18,10,12
2,Arkansas,AR,43,10,5,2,3,1,3,1,4,5,4,2,3
3,California,CA,398,36,49,25,20,32,31,36,22,28,62,27,30
4,Colorado,CO,116,6,10,12,6,16,8,4,12,15,10,5,12
5,Connecticut,CT,15,4,0,2,3,1,0,0,1,1,1,2,0
6,Delaware,DE,7,0,0,2,0,0,0,0,1,1,1,1,1
7,District of Columbia,DC,8,0,1,0,1,0,1,0,2,0,1,0,2
8,Florida,FL,250,41,16,25,14,20,9,32,18,18,26,17,14
9,Georgia,GA,68,5,5,9,10,4,4,8,7,8,5,1,2
10,Idaho,ID,36,2,1,2,6,3,2,9,0,3,2,3,3
11,Illinois,IL,86,12,2,6,3,9,13,7,10,9,3,5,7
12,Indiana,IN,67,6,5,7,2,6,3,9,10,10,3,3,3
13,Iowa,IA,23,1,1,4,0,2,3,1,5,1,2,0,3
14,Kansas,KS,20,1,1,2,1,2,2,3,2,1,3,1,1
15,Kentucky,KY,42,3,2,3,1,2,1,11,3,2,6,5,3
16,Louisiana,LA,31,5,1,5,3,1,0,1,3,3,3,4,2
17,Maine,ME,27,2,4,3,3,3,2,5,0,2,2,0,1
18,Massachusetts,MA,42,3,4,5,0,6,5,1,2,8,1,2,5
19,Michigan,MI,122,8,7,14,14,11,11,14,10,9,13,4,7
20,Minnesota,MN,50,4,1,4,4,3,2,9,3,4,7,8,1
21,Mississippi,MS,17,3,0,1,1,0,0,1,3,4,3,1,0
22,Missouri,MO,77,9,4,7,2,3,7,12,11,8,5,6,3
23,Montana,MT,20,3,2,2,1,1,0,2,1,2,4,0,2
24,Nebraska,NE,14,0,1,3,0,0,4,0,2,2,1,1,0
25,Nevada,NV,71,9,9,2,1,8,6,10,7,5,6,5,3
26,New Hampshire,NH,8,0,0,0,0,0,1,2,2,1,2,0,0
27,New Jersey,NJ,71,7,6,3,6,4,8,10,8,3,8,3,5
28,New Mexico,NM,48,4,9,3,1,2,0,6,5,7,4,3,4
29,New York,NY,119,4,9,12,11,9,11,19,12,13,3,12,4
30,North Carolina,NC,74,6,3,7,3,9,8,4,8,6,9,5,6
31,North Dakota,ND,8,0,1,1,0,1,1,2,1,0,0,1,0
32,Ohio,OH,113,10,4,5,3,11,9,13,13,13,13,9,10
33,Oklahoma,OK,43,7,2,1,1,6,3,7,2,1,6,4,3
34,Oregon,OR,106,9,4,5,2,10,11,19,10,18,6,9,3
35,Pennsylvania,PA,134,12,10,11,9,8,13,19,12,12,9,11,8
36,Rhode Island,RI,4,0,0,0,0,0,1,0,1,1,1,0,0
37,South Carolina,SC,43,6,2,2,6,3,5,2,5,5,3,0,4
38,South Dakota,SD,8,2,0,0,1,1,1,0,0,1,1,1,0
39,Tennessee,TN,65,4,3,4,6,11,5,7,5,6,6,3,5
40,Texas,TX,234,18,11,19,23,24,18,25,24,17,19,20,16
41,Utah,UT,37,3,4,3,2,2,2,5,6,1,3,4,2
42,Vermont,VT,4,0,0,0,0,1,1,1,0,0,0,1,0
43,Virginia,VA,57,3,2,6,6,5,3,5,2,4,9,5,7
44,Washington,WA,148,13,11,11,4,15,11,16,10,22,11,11,13
45,West Virginia,WV,21,2,1,3,1,0,1,3,3,2,1,1,3
46,Wisconsin,WI,62,4,2,6,4,4,7,11,4,4,2,7,7
47,Wyoming,WY,6,0,0,0,0,0,1,0,1,1,2,1,0
48,USA,USA,3252,302,237,273,206,279,250,361,284,301,311,226,222